IMAGE_PLACEHOLDER_TEMPLATE = '[image_placeholder | {index}]'
IMAGE_PLACEHOLDER_PATTERN = r'\[image_placeholder(?: \| \d+)?\]'
MATH_PLACEHOLDER_TEMPLATE = '[math_placeholder | {index}]'
MATH_PLACEHOLDER_PATTERN = r'\[math_placeholder(?: \| \d+)?\]'
MATH_PLACEHOLDER_INDEX_PATTERN = r'\[math_placeholder(?:\s*\|\s*(\d+))?\]'
MATH_TEMPLATE = '[{katex} | {index}]'
