FROM node:latest

RUN --mount=type=secret,id=git_token \
    git clone https://Luka958Pixion:$(cat /run/secrets/git_token)@github.com/Luka958Pixion/katex-validator.git katex-validator

WORKDIR /katex-validator

RUN npm install

EXPOSE 3000

CMD ["node", "main.js"]
