services:
  math-rag-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: math_rag_dev_container
    volumes:
      - ./:/workspaces:cached
      - venv_volume:/workspaces/.venv
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/workspaces/.env
      - ./.ssh/id_ed25519:/.ssh/id_ed25519
    ports:
      - ${PORT}:${PORT}
    command: sleep infinity

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio_data:/data  # causes deadlock errors when using put_object if mapped to local
    command: server /data

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/password
      JAVA_TOOL_OPTIONS: "-XX:UseSVE=0" # https://medium.com/%40luketn/java-on-docker-sigill-exception-on-mac-os-sequoia-15-2-9311e4775442
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant_storage:/qdrant/storage

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./.tmp/prometheus/data:/prometheus
    ports:
      - 9090:9090

  math-rag-jupyter:
    image: ghcr.io/luka958pixion/math_rag_jupyter:latest
    platform: linux/amd64
    environment:
      - PORT=7030
    ports:
      - ${JUPYTER_PORT}:7030
    restart: unless-stopped

  math-rag-katex:
    image: ghcr.io/luka958pixion/math_rag_katex:latest
    platform: linux/amd64
    environment:
      - PORT=7020
    ports:
      - ${KATEX_PORT}:7020
    restart: unless-stopped

  math-rag-apptainer:
    image: ghcr.io/luka958pixion/math_rag_apptainer:latest
    platform: linux/amd64
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=7010
    ports:
      - ${APPTAINER_PORT}:7010
    restart: unless-stopped

volumes:
  venv_volume:
  minio_data:
  mongo_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  qdrant_storage:
  prometheus_data:
  jupyter_sessions:
  apptainer_data:

configs:
  qdrant_config:
    content: |
      log_level: INFO