from .kc_prompt import KATEX_CORRECTION_PROMPT
from .kc_retry_prompt import KATEX_CORRECTION_RETRY_PROMPT
from .mec_prompt import MATH_EXPRESSION_CLASSIFICATION_PROMPT


__all__ = [
    'KATEX_CORRECTION_PROMPT',
    'KATEX_CORRECTION_RETRY_PROMPT',
    'MATH_EXPRESSION_CLASSIFICATION_PROMPT',
]
