BATCH_WAIT_AFTER_RATE_LIMIT_ERROR = 15
BATCH_INPUT_FILE_SIZE_LIMIT = 100  # in MB
BATCH_INPUT_FILE_SIZE_LIMIT_THRESHOLD = 0.8
BATCH_INPUT_FILE_SIZE_LIMIT_SCALED = (
    BATCH_INPUT_FILE_SIZE_LIMIT * BATCH_INPUT_FILE_SIZE_LIMIT_THRESHOLD
)
