from typing import Protocol

class ModelSpec(Protocol):
    def format_prompt(self, prompt: str) -> str: ...
    def formatting_func(self, x: str) -> str: ...
    def init_language_model(self, cfg: dict) -> object: ...
    def init_tokenizer(self, cfg: dict) -> object: ...
